'use client';

import { useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, Check, CheckCircle2, ChevronDown, Clock3, Mail, Sparkles, Users } from 'lucide-react';

const statuses = ['UG student', 'PG student', 'PhD / researcher', 'Working professional', 'Educator / academic', 'Quantum computing enthusiast', 'Other'];
const contributionOptions = ['Programs and events', 'Content and education', 'Research initiatives', 'Technology and website', 'Community and outreach', 'Partnerships and industry relations', 'Media and communication', 'Design and creative', 'Operations and strategy'];
const quantumAreas = ['Quantum algorithms', 'Quantum hardware', 'Quantum error correction / mitigation', 'Quantum machine learning', 'Quantum software and programming', 'Quantum communication / cryptography', 'Quantum sensing', 'Quantum education'];
const availability = ['Less than 1 hour / week', '1-2 hours / week', '3-5 hours / week', '5-10 hours / week', '10+ hours / week'];
const duration = ['A few weeks', '1-3 months', '3-6 months', '6-12 months', 'Open-ended, if the work is meaningful'];
const workStyles = ['Independently with clear outcomes', 'Collaboratively in a small team', 'A mix of independent and team work', 'I am still figuring this out'];
const quantumExperience = ['I am new to quantum technology', 'I have explored it through courses or self-study', 'I have completed projects or coursework', 'I have research or professional experience'];
const responsibility = ['Yes, I would be interested', 'Possibly, depending on the role', 'I prefer to focus on contributing for now'];
const yesNo = ['Yes', 'No', 'Not sure yet'];

type FormState = {
  fullName: string; email: string; phone: string; countryCity: string; currentStatus: string; institution: string; discipline: string;
  linkedinUrl: string; portfolioUrl: string; contributionAreas: string[]; primaryArea: string; ownershipIdea: string; skills: string;
  completedWork: string; evidence: string; quantumExperience: string; quantumAreas: string[]; availability: string; duration: string;
  workStyle: string; checkIns: string; timezone: string; whyQng: string; qngStrength: string; newInitiative: string;
  greaterResponsibility: string; mentoring: string; anythingElse: string; consent: boolean; contactConsent: boolean;
};

const initialForm: FormState = {
  fullName: '', email: '', phone: '', countryCity: '', currentStatus: '', institution: '', discipline: '', linkedinUrl: '', portfolioUrl: '', contributionAreas: [], primaryArea: '', ownershipIdea: '', skills: '', completedWork: '', evidence: '', quantumExperience: '', quantumAreas: [], availability: '', duration: '', workStyle: '', checkIns: '', timezone: '', whyQng: '', qngStrength: '', newInitiative: '', greaterResponsibility: '', mentoring: '', anythingElse: '', consent: false, contactConsent: false,
};

export default function JoinTeamPage() {
  const [form, setForm] = useState<FormState>(initialForm);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [error, setError] = useState('');
  const inputClass = 'w-full rounded-xl border border-slate-200 bg-white/80 px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-cyan-500 focus:ring-4 focus:ring-cyan-500/10';
  const labelClass = 'mb-2 block text-sm font-semibold text-slate-800';
  const selectClass = `${inputClass} appearance-none pr-11`;
  const update = <K extends keyof FormState>(key: K, value: FormState[K]) => setForm((current) => ({ ...current, [key]: value }));
  const toggle = (key: 'contributionAreas' | 'quantumAreas', value: string, max?: number) => {
    const values = form[key];
    if (values.includes(value)) update(key, values.filter((item) => item !== value));
    else if (!max || values.length < max) update(key, [...values, value]);
  };
  const selectField = (id: keyof FormState, label: string, options: string[], required = true) => (
    <div><label htmlFor={id} className={labelClass}>{label}{!required && <span className="font-normal text-slate-400"> (optional)</span>}</label><div className="relative"><select id={id} required={required} className={selectClass} value={String(form[id])} onChange={(event) => update(id, event.target.value as never)}><option value="" disabled>Select an option</option>{options.map((option) => <option key={option} value={option}>{option}</option>)}</select><ChevronDown className="pointer-events-none absolute right-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /></div></div>
  );
  const textField = (id: keyof FormState, label: string, helper?: string, required = true) => (
    <div><label htmlFor={id} className={labelClass}>{label}{!required && <span className="font-normal text-slate-400"> (optional)</span>}</label>{helper && <p className="mb-2 text-xs leading-5 text-slate-500">{helper}</p>}<textarea id={id} required={required} rows={5} className={inputClass} value={String(form[id])} onChange={(event) => update(id, event.target.value as never)} /></div>
  );
  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setError('');
    if (form.contributionAreas.length === 0 || form.contributionAreas.length > 2) return setError('Select one or two contribution areas.');
    if (!form.consent) return setError('Please accept the contributor role consent before submitting.');
    setIsSubmitting(true);
    try {
      const response = await fetch('/api/team-applications', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) });
      const data = await response.json();
      if (!response.ok || !data.success) throw new Error(data.message || 'Something went wrong. Please try again.');
      setSubmitted(true);
    } catch (submitError: any) { setError(submitError.message || 'Unable to submit your application right now.'); }
    finally { setIsSubmitting(false); }
  };

  return (
    <main className="min-h-screen overflow-hidden bg-[#f4f8f7] text-slate-950">
      <div className="absolute inset-x-0 top-0 h-[520px] bg-[radial-gradient(circle_at_18%_5%,rgba(148,163,184,0.14),transparent_34%),radial-gradient(circle_at_82%_8%,rgba(203,213,225,0.18),transparent_30%)]" />
      <header className="relative z-10 border-b border-slate-900/10 bg-white/60 px-5 py-4 backdrop-blur-md sm:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between"><Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-700 transition hover:text-slate-950"><ArrowLeft className="h-4 w-4" /> Back home</Link><span className="font-mono text-[10px] uppercase tracking-[0.24em] text-slate-500">QNexus / Contributors</span></div></header>
      <div className="relative z-10 mx-auto grid max-w-6xl gap-10 px-5 py-12 sm:px-8 lg:grid-cols-[0.75fr_1.25fr] lg:gap-16 lg:py-20">
        <section className="lg:sticky lg:top-10 lg:self-start"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-cyan-700/15 bg-white/70 px-3 py-1.5 text-[11px] font-mono uppercase tracking-wider text-cyan-800"><Sparkles className="h-3.5 w-3.5" /> Contributor application</div><h1 className="max-w-xl text-5xl font-bold leading-[0.98] tracking-[-0.04em] text-slate-950 sm:text-6xl">Build something <span className="text-cyan-700">useful with us.</span></h1><p className="mt-6 max-w-md text-lg leading-8 text-slate-600">Help build the next generation of quantum talent, opportunity, and collaboration.</p><p className="mt-4 max-w-md text-sm leading-6 text-slate-500">We value initiative, reliability, curiosity, and ownership. You do not need to be a quantum expert for most contributor roles.</p><div className="mt-8 grid max-w-md grid-cols-3 gap-2 border-y border-slate-900/10 py-5 text-center"><div><p className="text-2xl font-bold">01</p><p className="mt-1 text-[10px] font-mono uppercase tracking-wider text-slate-500">Apply</p></div><div><p className="text-2xl font-bold">02</p><p className="mt-1 text-[10px] font-mono uppercase tracking-wider text-slate-500">Contribute</p></div><div><p className="text-2xl font-bold">03</p><p className="mt-1 text-[10px] font-mono uppercase tracking-wider text-slate-500">Grow</p></div></div><div className="mt-10 grid gap-3 text-sm text-slate-700"><div className="flex items-center gap-3 rounded-xl border border-slate-900/10 bg-white/60 p-4"><Users className="h-5 w-5 text-emerald-600" /><span>Work on real QNG programs and initiatives</span></div><div className="flex items-center gap-3 rounded-xl border border-slate-900/10 bg-white/60 p-4"><Mail className="h-5 w-5 text-cyan-600" /><span>Build demonstrable work for your portfolio</span></div><div className="flex items-center gap-3 rounded-xl border border-slate-900/10 bg-white/60 p-4"><Clock3 className="h-5 w-5 text-amber-600" /><span>Choose a contribution that fits your schedule</span></div></div></section>
        <section className="rounded-3xl border border-slate-900/10 bg-white p-6 shadow-[0_24px_80px_rgba(15,23,42,0.08)] sm:p-10">
          {submitted ? <div className="flex min-h-[520px] flex-col items-center justify-center text-center"><div className="mb-6 flex h-16 w-16 items-center justify-center rounded-full bg-emerald-100 text-emerald-700"><CheckCircle2 className="h-8 w-8" /></div><h2 className="text-3xl font-bold tracking-tight">Thank you for stepping forward.</h2><p className="mt-4 max-w-md leading-7 text-slate-600">Your contributor application is safely with our team. We have sent a confirmation to <strong>{form.email}</strong> and will review what you would like to build with us.</p><Link href="/" className="mt-8 inline-flex items-center gap-2 rounded-full bg-slate-950 px-5 py-3 text-sm font-semibold text-white transition hover:bg-slate-800">Return home <ArrowRight className="h-4 w-4" /></Link></div> : <form onSubmit={handleSubmit} className="space-y-10">
            <div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-cyan-700">Contributor application</p><h2 className="mt-2 text-2xl font-bold tracking-tight">Quantum Nexus Global â€” Contributor Application</h2><p className="mt-2 text-sm leading-6 text-slate-500">Tell us where you can take ownership. This is for contributors, not a general membership, mentorship, or fellowship application.</p></div>
            <fieldset className="space-y-5"><legend className="text-xl font-bold">1. About you</legend><div className="grid gap-5 sm:grid-cols-2"><div><label htmlFor="fullName" className={labelClass}>Full name</label><input id="fullName" required className={inputClass} value={form.fullName} onChange={(event) => update('fullName', event.target.value)} /></div><div><label htmlFor="email" className={labelClass}>Email address</label><input id="email" required type="email" className={inputClass} value={form.email} onChange={(event) => update('email', event.target.value)} /></div><div><label htmlFor="phone" className={labelClass}>Phone / WhatsApp number<span className="font-normal text-slate-400"> (optional)</span></label><input id="phone" type="tel" className={inputClass} value={form.phone} onChange={(event) => update('phone', event.target.value)} /></div><div><label htmlFor="countryCity" className={labelClass}>Country / city</label><input id="countryCity" required className={inputClass} value={form.countryCity} onChange={(event) => update('countryCity', event.target.value)} /></div>{selectField('currentStatus', 'Current status', statuses)}<div><label htmlFor="institution" className={labelClass}>Institution / organization<span className="font-normal text-slate-400"> (optional)</span></label><input id="institution" className={inputClass} value={form.institution} onChange={(event) => update('institution', event.target.value)} /></div><div><label htmlFor="discipline" className={labelClass}>Current field / discipline</label><input id="discipline" required placeholder="Physics, design, business, etc." className={inputClass} value={form.discipline} onChange={(event) => update('discipline', event.target.value)} /></div><div><label htmlFor="linkedinUrl" className={labelClass}>LinkedIn profile<span className="font-normal text-slate-400"> (recommended)</span></label><input id="linkedinUrl" type="url" className={inputClass} value={form.linkedinUrl} onChange={(event) => update('linkedinUrl', event.target.value)} /></div><div className="sm:col-span-2"><label htmlFor="portfolioUrl" className={labelClass}>GitHub / portfolio / website / Google Scholar<span className="font-normal text-slate-400"> (optional)</span></label><input id="portfolioUrl" type="url" className={inputClass} value={form.portfolioUrl} onChange={(event) => update('portfolioUrl', event.target.value)} /></div></div></fieldset>
            <fieldset className="space-y-5"><legend className="text-xl font-bold">2. Where would you like to contribute?</legend><div><p className={labelClass}>QNG areas you are most interested in contributing to</p><p className="mb-3 text-xs text-slate-500">Select no more than two.</p><div className="grid gap-2 sm:grid-cols-2">{contributionOptions.map((option) => { const selected = form.contributionAreas.includes(option); return <button type="button" key={option} onClick={() => toggle('contributionAreas', option, 2)} className={`flex items-center gap-3 rounded-xl border px-3.5 py-3 text-left text-sm transition ${selected ? 'border-emerald-500 bg-emerald-50 text-emerald-950' : 'border-slate-200 hover:border-slate-300'}`}><span className={`flex h-5 w-5 shrink-0 items-center justify-center rounded-md border ${selected ? 'border-emerald-600 bg-emerald-600 text-white' : 'border-slate-300'}`}>{selected && <Check className="h-3.5 w-3.5" />}</span>{option}</button>; })}</div></div>{selectField('primaryArea', 'If selected, which one area would you most like to own?', contributionOptions)}{textField('ownershipIdea', 'What is one specific thing you would like to build, improve, or take ownership of at QNG?', 'Be specific. For example: â€œI would like to curate a weekly opportunities databaseâ€ or â€œI can coordinate speaker outreach.â€')}</fieldset>
            <fieldset className="space-y-5"><legend className="text-xl font-bold">3. Experience and evidence</legend>{textField('skills', 'What relevant skills or experience would you bring to QNG?')}{textField('completedWork', 'Tell us about one thing you have previously completed that demonstrates those skills.', 'This can be a project, research work, article, event, website, design, video, outreach campaign, or open-source contribution.')}{textField('evidence', 'Please share any relevant links or evidence.', 'LinkedIn, GitHub, publication, article, design portfolio, event page, video, certificate, etc.', false)}{selectField('quantumExperience', 'Which best describes your experience with quantum technology?', quantumExperience)}<div><p className={labelClass}>Areas of quantum technology you know or want to explore<span className="font-normal text-slate-400"> (optional)</span></p><div className="grid gap-2 sm:grid-cols-2">{quantumAreas.map((area) => { const selected = form.quantumAreas.includes(area); return <button type="button" key={area} onClick={() => toggle('quantumAreas', area)} className={`rounded-xl border px-3.5 py-3 text-left text-sm transition ${selected ? 'border-cyan-500 bg-cyan-50 text-cyan-950' : 'border-slate-200 hover:border-slate-300'}`}>{selected ? 'âœ“ ' : ''}{area}</button>; })}</div></div></fieldset>
            <fieldset className="space-y-5"><legend className="text-xl font-bold">4. Working style and commitment</legend><div className="grid gap-5 sm:grid-cols-2">{selectField('availability', 'How much time can you realistically contribute?', availability)}{selectField('duration', 'How long can you realistically remain involved?', duration)}{selectField('workStyle', 'Which best describes how you prefer to work?', workStyles)}{selectField('checkIns', 'Are you comfortable with regular check-ins and agreed deliverables?', yesNo)}<div><label htmlFor="timezone" className={labelClass}>Timezone generally available in<span className="font-normal text-slate-400"> (optional)</span></label><input id="timezone" className={inputClass} placeholder="IST / UTC+5:30" value={form.timezone} onChange={(event) => update('timezone', event.target.value)} /></div></div></fieldset>
            <fieldset className="space-y-5"><legend className="text-xl font-bold">5. Why QNG?</legend>{textField('whyQng', 'Why do you specifically want to contribute to Quantum Nexus Global?', 'Please avoid generic answers such as â€œI am passionate about quantum.â€ Tell us why QNG interests you specifically.')}{textField('qngStrength', 'What do you think QNG should become particularly good at?')}{textField('newInitiative', 'If you could start one new QNG initiative, what would it be?', undefined, false)}</fieldset>
            <fieldset className="space-y-5"><legend className="text-xl font-bold">6. Future growth</legend>{selectField('greaterResponsibility', 'Would you be interested in taking greater responsibility if your contribution goes well?', responsibility)}{selectField('mentoring', 'Would you be interested in mentoring or supervising others in the future, if qualified?', yesNo, false)}</fieldset>
            <fieldset className="space-y-5"><legend className="text-xl font-bold">7. Final</legend>{textField('anythingElse', 'Anything else you would like us to know?', undefined, false)}<label className="flex items-start gap-3 text-sm leading-6 text-slate-600"><input required type="checkbox" className="mt-1 h-4 w-4 accent-cyan-600" checked={form.consent} onChange={(event) => update('consent', event.target.checked)} />I understand that submitting this form does not guarantee selection. QNG Contributor roles are voluntary, and continued participation or progression into QNG Team roles depends on contribution, reliability, and organizational needs.</label><label className="flex items-start gap-3 text-sm leading-6 text-slate-600"><input type="checkbox" className="mt-1 h-4 w-4 accent-cyan-600" checked={form.contactConsent} onChange={(event) => update('contactConsent', event.target.checked)} />I consent to Quantum Nexus Global contacting me about this application and relevant QNG opportunities.</label></fieldset>
            {error && <p className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</p>}<button disabled={isSubmitting} type="submit" className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-slate-950 px-5 py-4 text-sm font-semibold text-white transition hover:bg-cyan-700 disabled:cursor-wait disabled:opacity-60">{isSubmitting ? 'Sending your application...' : 'Submit contributor application'} <ArrowRight className="h-4 w-4" /></button><p className="text-center text-xs leading-5 text-slate-500">Your information is used to review your application and connect you with the QNexus team.</p>
          </form>}
        </section>
      </div>
    </main>
  );
}
